#!/bin/bash

set -e

echo 'post-checkout hook'

prevHEAD=$1
newHEAD=$2
checkoutType=$3

[[ $checkoutType == 1 ]] && checkoutType='branch' ||
                            checkoutType='file' ;

#echo 'Checkout type: '$checkoutType
#echo ' prev HEAD: '`git name-rev --name-only $prevHEAD`
#echo ' new HEAD: '`git name-rev --name-only $newHEAD`

cd /home/legolas/dev/artemis/nad/sources/daimler-artemis
echo "Build ${CSCOPE_DB}"
cscope -Rb -f${CSCOPE_DB}
cd -
